(import (rnrs)
        (mosh test)
        (memcached))

(let ([conn (memcached-connect "localhost" "11211")])
  (memcached-set! conn "Hello" 0 0 "World!")
  (memcached-set! conn "Hi" 0 0 "Japan!")
  (memcached-set! conn  "Hige" 0 0 "pon")
  (memcached-set! conn  "my" 0 0 '(name is higepon))
  (test-equal "World!" (memcached-get conn "Hello"))
  (test-equal "Japan!" (memcached-get conn "Hi"))
  (test-equal "pon" (memcached-get conn "Hige"))
  (test-equal '(name is higepon) (memcached-get conn "my"))
  (test-equal '(("Hello" . "World!") ("Hi" . "Japan!")) (memcached-gets conn "mio:range-search" "He" "Hi" "50"))
  (test-results)
)
