#!/bin/sh
### Copyright (C) 2009 Higepon <higepon@users.sourceforge.jp>.
### All rights reserved.
###
### Redistribution and use in source and binary forms, with or without
### modification, are permitted provided that the following conditions
### are met:
###
### 1. Redistributions of source code must retain the above copyright
###    notice, this list of conditions and the following disclaimer.
### 2. Redistributions in binary form must reproduce the above
###    copyright notice, this list of conditions and the following
###    disclaimer in the documentation and/or other materials provided
###    with the distribution.
###
### THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS
### OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
### WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
### ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
### DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
### DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
### GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
### INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
### WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
### NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
### SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

DEFAULT_NODE_NAME=mio1
DEFAULT_COOKIE_NAME=mio
DEFAULT_LISTEN_PORT=11211
DEFAULT_MAX_LEVEL=3

opt_cookie=
opt_name=
opt_port=
opt_introducer=
opt_verbose=false
opt_maxlevel=
while getopts 'n:p:i:vc:m:' OPTION
do
  case $OPTION in
  m)    opt_maxlevel="$OPTARG"
        ;;
  c)    opt_cookie="$OPTARG"
        ;;
  n)    opt_name="$OPTARG"
        ;;
  p)    opt_port="$OPTARG"
        ;;
  v)    opt_verbose=true
        ;;
  i)    opt_introducer="$OPTARG"
        ;;
  ?)    printf "Usage: %s: [-n node_name] [-p port] [-i introducer_name] [-c cookie] [-m maxlevel]\n" $(basename $0) >&2
        exit 2
        ;;
  esac
done
shift $(($OPTIND - 1))
mio_cookie=${opt_cookie:-"$DEFAULT_COOKIE_NAME"}
mio_name=${opt_name:-"$DEFAULT_NODE_NAME"}
mio_name="${mio_name}@"`hostname -s`".local"
mio_port=${opt_port:-"$DEFAULT_LISTEN_PORT"}
mio_introducer=${opt_introducer:-"false"}
mio_maxlevel=${opt_maxlevel:-"$DEFAULT_MAX_LEVEL"}
mio_verbose=$opt_verbose


    erl +K true -name $mio_name \
        +P 134217727 \
        -setcookie $mio_cookie \
        -boot start_sasl -config conf/dev_log +W w \
        -mio \
        -noshell \
        -noinput \
        -pa ebin mio \
        -s mio_app start \
        -mio debug $mio_verbose port $mio_port boot_node $mio_introducer maxlevel $mio_maxlevel
