#!/bin/sh
### Copyright (C) 2009 Higepon <higepon@users.sourceforge.jp>.
### All rights reserved.
###
### Redistribution and use in source and binary forms, with or without
### modification, are permitted provided that the following conditions
### are met:
###
### 1. Redistributions of source code must retain the above copyright
###    notice, this list of conditions and the following disclaimer.
### 2. Redistributions in binary form must reproduce the above
###    copyright notice, this list of conditions and the following
###    disclaimer in the documentation and/or other materials provided
###    with the distribution.
###
### THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS
### OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
### WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
### ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
### DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
### DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
### GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
### INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
### WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
### NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
### SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

DEFAULT_NODE_NAME=mio1
DEFAULT_COOKIE_NAME=mio
DEFAULT_LISTEN_PORT=11211
DEFAULT_MAX_LEVEL=3
DEFAULT_LOG_DIR=`pwd`

. `dirname $0`/mio-env
MIO_EBIN_ROOT="${MIO_HOME}/ebin"

opt_cookie=
opt_name=
opt_port=
opt_log_dir=
opt_introducer=
opt_verbose=false
opt_maxlevel=
opt_detached=

while getopts 'dn:p:i:vc:m:l:' OPTION
do
  case $OPTION in
  m)    opt_maxlevel="$OPTARG"
        ;;
  c)    opt_cookie="$OPTARG"
        ;;
  n)    opt_name="$OPTARG"
        ;;
  p)    opt_port="$OPTARG"
        ;;
  l)    opt_log_dir="$OPTARG"
        ;;
  v)    opt_verbose=true
        ;;
  d)    opt_detached="1"
        ;;
  i)    opt_introducer="$OPTARG"
        ;;
  ?)    printf "Usage: %s: [-n node_name] [-l log_dir] [-v:verbose mode] [-p port] [-i introducer_name] [-c cookie] [-m maxlevel] [-d:detached mode]\n" $(basename $0) >&2
        exit 2
        ;;
  esac
done
shift $(($OPTIND - 1))
mio_cookie=${opt_cookie:-"$DEFAULT_COOKIE_NAME"}
mio_name=${opt_name:-"$DEFAULT_NODE_NAME"}
mio_name="${mio_name}@"`hostname -s`".local"
mio_log_dir=${opt_log_dir:-"$DEFAULT_LOG_DIR"}
mio_port=${opt_port:-"$DEFAULT_LISTEN_PORT"}
mio_introducer=${opt_introducer:-"false"}
mio_maxlevel=${opt_maxlevel:-"$DEFAULT_MAX_LEVEL"}
mio_verbose=$opt_verbose
mio_detached=${opt_detached:+"-detached"}


#   +A 30                   : Sets the number of threads in async thread pool, valid range is 0-1024. Default is 0.
#   +K true                 : Use the kernel poll functionality
#   +P 134217727            : Sets the maximum number of concurrent processes.
#   +W w                    : warning messages are sent as warning.
#   -noshell                : This flag makes it possible to have the Erlang runtime system as a component in a series of UNIX pipes.
#   -noinput                : Ensures that the Erlang runtime system never tries to read any input.
#   -setcookie $mio_cookie  : Sets the magic cookie of the node to Cookie
#   -config conf/dev_log    : Sets the config file used to configure applications.
#    -kernel                : Options to kernel application, which are passed to inet module

# config file path
erl +A 30 \
    +K true \
    +P 134217727 \
    +W w \
    -noshell \
    -noinput \
    -setcookie $mio_cookie \
    -kernel inet_default_listen_options [{nodelay,true},{sndbuf,16384},{recbuf,4096}] \
    -kernel inet_default_connect_options [{nodelay,true}] \
    -name $mio_name \
    -pa ${MIO_EBIN_ROOT} \
    -s mio_app start \
    ${mio_detached} \
    -mio debug $mio_verbose \
         port $mio_port \
         boot_node $mio_introducer \
         maxlevel $mio_maxlevel \
         log_dir "\"$mio_log_dir\"" \
         verbose $mio_verbose

